- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: sunday

        - type: weather
          location: Guangzhou
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        # - type: rss
        #   limit: 10
        #   collapse-after: 3
        #   cache: 12h
        #   feeds:
        #     - url: https://selfh.st/rss/
        #       title: selfh.st
        #     - url: https://ciechanow.ski/atom.xml
        #     - url: https://www.joshwcomeau.com/rss.xml
        #       title: Josh Comeau
        #     - url: https://samwho.dev/rss.xml
        #     - url: https://ishadeed.com/feed.xml
        #       title: Ahmad Shadeed

        # - type: twitch-channels
        #   channels:
        #     - theprimeagen
        #     - j_blow
        #     - piratesoftware
        #     - cohhcarnage
        #     - christitustech
        #     - EJ_SA

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            # - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            # - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
            - gbFU6KoEASU&t=18s # optimun

        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: custom-api
          title: Tailscale Devices
          title-url: https://login.tailscale.com/admin/machines
          url: https://api.tailscale.com/api/v2/tailnet/-/devices
          headers:
            Authorization: Bearer ${tskey-api-kJUhFoEUAe11CNTRL-YZbPaEF3phdmxBYa2JtHhdGNhBgMeT91}
          cache: 10m
          template: |
            <style>
              .device-info-container {
                position: relative;
                overflow: hidden;
                height: 1.5em;
              }

              .device-info {
                display: flex;
                transition: transform 0.2s ease, opacity 0.2s ease;
              }

              .device-ip {
                position: absolute;
                top: 0;
                left: 0;
                transform: translateY(-100%);
                opacity: 0;
                transition: transform 0.2s ease, opacity 0.2s ease;
              }

              .device-info-container:hover .device-info {
                transform: translateY(100%);
                opacity: 0;
              }

              .device-info-container:hover .device-ip {
                transform: translateY(0);
                opacity: 1;
              }

              .update-indicator {
                width: 8px;
                height: 8px;
                border-radius: 50%;
                background-color: var(--color-primary);
                display: inline-block;
                margin-left: 4px;
                vertical-align: middle;
              }

              .offline-indicator {
                width: 8px;
                height: 8px;
                border-radius: 50%;
                background-color: var(--color-negative);
                display: inline-block;
                margin-left: 4px;
                vertical-align: middle;
              }

              .device-name-container {
                display: flex;
                align-items: center;
                gap: 8px;
              }

              .indicators-container {
                display: flex;
                align-items: center;
                gap: 4px;
              }
            </style>
            <ul class="list list-gap-10 collapsible-container" data-collapse-after="4">
              {{ range .JSON.Array "devices" }}
              <li>
                <div class="flex items-center gap-10">
                  <div class="device-name-container grow">
                    <span class="size-h4 block text-truncate color-primary">
                      {{ findMatch "^([^.]+)" (.String "name") }}
                    </span>
                    <div class="indicators-container">
                      {{ if (.Bool "updateAvailable") }}
                      <span class="update-indicator" data-popover-type="text" data-popover-text="Update Available"></span>
                      {{ end }}

                      {{ $lastSeen := .String "lastSeen" | parseTime "rfc3339" }}
                      {{ if not ($lastSeen.After (offsetNow "-10s")) }}
                      {{ $lastSeenTimezoned := $lastSeen.In now.Location }}
                      <span class="offline-indicator" data-popover-type="text"
                        data-popover-text="Offline - Last seen {{ $lastSeenTimezoned.Format " Jan 2 3:04pm" }}"></span>
                      {{ end }}

                    </div>
                  </div>
                </div>
                <div class="device-info-container">
                  <ul class="list-horizontal-text device-info">
                    <li>{{ .String "os" }}</li>
                    <li>{{ .String "user" }}</li>
                  </ul>
                  <div class="device-ip">
                    {{ .String "addresses.0"}}
                  </div>
                </div>
              </li>
              {{ end }}
            </ul>


        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            # - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing
